version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn compile
      - mvn test -DargLine="-Dspring.profiles.active=cicd"
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/demo-0.0.1.jar