branch-defaults:
  master:
    environment: custom-time
global:
  application_name: elastic-demo-time-v1.6
  default_ec2_keyname: Elasticdemotimev16-env
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  sc: git