version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    resource_class: medium
    steps:
      - run: sudo apt-get update
      - run: sudo debconf-set-selections \<<< 'mysql-server mysql-server/root_password password 123456789'
      - run: sudo debconf-set-selections \<<< 'mysql-server mysql-server/root_password_again password 123456789'
      - run: sudo apt-get install mysql-server
      - run: sudo systemctl start mysql
      - run: sudo mysql -u root -p123456789
      - run: mysql -e "SET @@global.time_zone = UTC"
      - run: mysql -e "create database demo_time_test"