version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    resource_class: small
    steps:
      - run: sudo apt-get update
      - run: sudo debconf-set-selections << 'mysql-server mysql-server/root_password password 123456789'
      - run: sudo debconf-set-selections << 'mysql-server mysql-server/root_password_again password 123456789'
      - run: sudo apt-get install mysql-server
      - run: sudo systemctl start mysql
      - run: /usr/bin/mysql -u root -p