version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    resource_class: medium
    steps:
      - run: sudo apt-get update
      - run: sudo debconf-set-selections \<<< 'mysql-server mysql-server/root_password password 123456789'
      - run: sudo debconf-set-selections \<<< 'mysql-server mysql-server/root_password_again password 123456789'
      - run: sudo apt-get install mysql-server
      - run: sudo systemctl start mysql
      - run: mysql -u root -p123456789 -e "SET @@global.time_zone = '+02:00'"
      - run: mysql -u root -p123456789 -e "create database demo_time_test"
      - run: mysql  -u root -p123456789 -e "exit"
      - run: sudo apt-get install oracle-java17-installer oracle-java17-set-default curl -y

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
              # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline

        # run tests!
      - run: mvn -e test -DargLine="-Dspring.profiles.active=cicd"